### ISSUE TITLE
Make out coming value of collection.getPages(identifiers:) sorted by input

### ISSUE THREAD

**Issue by tscholze** [anfema/ion-client-ios#22]
**Problem**
The method to get pages of provided page identifiers in `ion.swift:326` returns a sorted list by the `position` attribute of each page.

In this case, this is an incorrect operation due to the fact that the provided identifiers must not have the same parent page. 

**What it should be**
We have to sort the out coming list by its input parameter page identifier indeces.

**Keep in mind**
We have to check / update all ION-based apps to the new return sorting if we change it.

**Follow up tasks**
Update comment of `.children method` that indicates the sorting

**To Discuss**
@p-fischer mentioned that the Android ION client does not sort by position on a page because their client assume that this field is not available.

**Comment by tscholze** [comment]
Quick fix for BCG:

```
var sorted = [Page?]()
for inputId in identifiers {
    sorted.append(pages.first(where: { $0.identifier == inputId }))
}
                
return sorted.compactMap( { $0 }),
```

**Comment by tscholze** [comment]
@mredlin We should discuss this with Peter and maybe Roland. It seems that not all ION / Wagtail installations supports the `position` attribute.

**Comment by mredlin** [comment]
Can be tested with version 6.2.0
